// AUTO-GENERADO desde templates de candidatos — no editar manualmente
// Clave: "ANIO_CARGO_NOMBRE CANDIDATO EN MAYÚSCULAS"

// Uso en data.js: resolverPartido(parnombre, cannombre, anio, cargo)

const CANDIDATOS_PARTIDO = {

    // ── 2011 ALCALDE ──
    '2011_alcalde_ALEJANDRO MUNOZ SANDOVAL': 'Partido Liberal Colombiano',
    '2011_alcalde_ALSILVER SIERRA MENDIETA': 'Partido Conservador Colombiano',
    '2011_alcalde_AMPARO OLARTE ALCANTAR': 'Partido de la U',
    '2011_alcalde_ANA HILDA PINZON DE MARTINEZ': 'Alianza Verde',
    '2011_alcalde_ANA ISABEL BERNAL CAMARGO': 'Alianza Verde',
    '2011_alcalde_ANA YOLANDA HERNANDEZ DAZA': 'Alianza Verde',
    '2011_alcalde_ARMANDO TARAZONA GALLO': 'Cambio Radical',
    '2011_alcalde_BENITO QUINTERO PINTO': 'Partido Liberal Colombiano',
    '2011_alcalde_BERNARDO ANDRES PULIDO GARCIA': 'Partido de la U',
    '2011_alcalde_CARLOS ANDRES COCUNUBO BLANCO': 'Partido de la U',
    '2011_alcalde_CARLOS ARTURO RAMIREZ BAYONA': 'Partido Conservador Colombiano',
    '2011_alcalde_CARLOS ARTURO TRIANA VEGA': 'Partido Conservador Colombiano',
    '2011_alcalde_CARLOS EDUARDO BORRAS BUITRAGO': 'Partido Liberal Colombiano',
    '2011_alcalde_CARLOS EDUARDO TOVAR GALINDO': 'Partido de la U',
    '2011_alcalde_CARLOS ERNESTO TORRES AGUIRRE': 'Alianza Verde',
    '2011_alcalde_CESAR EDUARDO PALACIOS FLORIDO': 'Partido de la U',
    '2011_alcalde_CESAR ORLANDO LOPEZ BACCA': 'Partido Conservador Colombiano',
    '2011_alcalde_CLARA INES SAAVEDRA BEJARANO': 'Partido Liberal Colombiano',
    '2011_alcalde_CONSTANZA ISABEL RAMIREZ ACEVEDO': 'Partido de la U',
    '2011_alcalde_DALILA YAZMIN PAMPLONA PACHECO': 'Partido de Integración Nacional',
    '2011_alcalde_DORA BELKIS GOMEZ CETINA': 'Partido Conservador Colombiano',
    '2011_alcalde_EDGAR HERNAN MORON TRIANA': 'Alianza Verde',
    '2011_alcalde_EDGAR HERNANDO RUIZ PULIDO': 'Partido de la U',
    '2011_alcalde_EDGAR PARRA': 'Partido Conservador Colombiano',
    '2011_alcalde_EDUAR ESCAMILLA CORREA': 'Partido de la U',
    '2011_alcalde_ERMES URIEL COMBITA SANTANA': 'Partido de la U',
    '2011_alcalde_EVER NINO CUERVO': 'Partido Conservador Colombiano',
    '2011_alcalde_EZEQUIEL GUERRA PARADA': 'Partido de la U',
    '2011_alcalde_FABIAN BULLA SANCHEZ': 'Cambio Radical',
    '2011_alcalde_FABIAN CAMILO IGUA ROBLES': 'Movimiento Ciudadano',
    '2011_alcalde_FABIO ERNESTO HUERTAS LEGUIZAMON': 'Partido Conservador Colombiano',
    '2011_alcalde_FERNANDO FLOREZ ESPINOSA': 'Alianza Verde',
    '2011_alcalde_FERNANDO RUBIO LOPEZ': 'Partido de la U',
    '2011_alcalde_FLORENTINO TORRES SANABRIA': 'ASI',
    '2011_alcalde_GERMAN DARIO CASTANEDA AGUDELO': 'Cambio Radical',
    '2011_alcalde_GERSON AYMER RUIZ CARRENO': 'Partido Liberal Colombiano',
    '2011_alcalde_GIOVANNI DIAZ RAMOS': 'Movimiento Ciudadano',
    '2011_alcalde_GONZALO ALFREDO CORTES CANON': 'Partido Liberal Colombiano',
    '2011_alcalde_GONZALO CASTRO TRIANA': 'Partido de Integración Nacional',
    '2011_alcalde_HECTOR ALFONSO GARCIA GARCIA': 'Cambio Radical',
    '2011_alcalde_HECTOR MAURICIO CUEVAS BERRIO': 'Alianza Verde',
    '2011_alcalde_HENRY ARMANDO SANCHEZ FORERO': 'ASI',
    '2011_alcalde_HERNAN ALONSO ACOSTA MEDINA': 'Alianza Verde',
    '2011_alcalde_HERNANDO ABRAHAN PEREZ FERNANDEZ': 'Cambio Radical',
    '2011_alcalde_HUGO HUERTAS ROMERO': 'Partido Conservador Colombiano',
    '2011_alcalde_HUGO PERALTA GOMEZ': 'Partido de la U',
    '2011_alcalde_IMER YARIDMA MURCIA MONROY': 'Alianza Verde',
    '2011_alcalde_JAIRO CORREA ACEVEDO': 'Partido de la U',
    '2011_alcalde_JAIRO RUIZ SALAZAR': 'Partido de la U',
    '2011_alcalde_JAVIER ALFONSO PUENTES DIAZ': 'Partido de la U',
    '2011_alcalde_JESUS ESTEBAN RIVERA MONTANA': 'Alianza Verde',
    '2011_alcalde_JESUS NOE RIVEROS LOPEZ': 'Partido de la U',
    '2011_alcalde_JHON FREDY CRISTANCHO BERDUGO': 'Partido de la U',
    '2011_alcalde_JHON JAIRO ALONSO RINCON': 'Partido Liberal Colombiano',
    '2011_alcalde_JORGE ANDRES ALARCON AVELLA': 'Partido de la U',
    '2011_alcalde_JORGE ENRIQUE ALBARRACIN VARGAS': 'Partido de la U',
    '2011_alcalde_JORGE VIDAL MARTIN MARTIN': 'Partido Conservador Colombiano',
    '2011_alcalde_JOSE GILBERTO CARO DUITAMA': 'Partido Liberal Colombiano',
    '2011_alcalde_JOSE GIOVANY PINZON BAEZ': 'Partido de la U',
    '2011_alcalde_JOSE HERNAN SIERRA BUITRAGO': 'Cambio Radical',
    '2011_alcalde_JOSE IGNACIO CAMACHO SIABATO': 'Partido Conservador Colombiano',
    '2011_alcalde_JOSE MAXIMINO SUAREZ LEON': 'Partido de la U',
    '2011_alcalde_JOSE MOISES AGUIRRE SANABRIA': 'Partido Liberal Colombiano',
    '2011_alcalde_JOSE ROBERTO SALINAS TORRES': 'Partido Conservador Colombiano',
    '2011_alcalde_JOSE SAMUEL MEDINA ALFONSO': 'Partido Conservador Colombiano',
    '2011_alcalde_JOSE VICENTE VARGAS PATINO': 'Partido Conservador Colombiano',
    '2011_alcalde_JOSE WILMAR LEAL ABRIL': 'Partido Liberal Colombiano',
    '2011_alcalde_JUAN ALCIBIADES CELY AMAYA': 'Partido Conservador Colombiano',
    '2011_alcalde_JUAN DIEGO MORALES CALDERON': 'Partido de la U',
    '2011_alcalde_JUSTO PASTOR GOYENECHE HERRERA': 'Partido Conservador Colombiano',
    '2011_alcalde_LIBIA MARIELA LANCHEROS DURAN': 'Partido de la U',
    '2011_alcalde_LUIS ALBERTO APONTE GOMEZ': 'Alianza Verde',
    '2011_alcalde_LUIS ALBERTO CASTEBLANCO QUINCOS': 'Partido Liberal Colombiano',
    '2011_alcalde_LUIS CARLOS SALAZAR ACOSTA': 'Partido Conservador Colombiano',
    '2011_alcalde_LUIS EDILBERTO PEDRAZA PUERTO': 'Partido Conservador Colombiano',
    '2011_alcalde_LUIS ERNESTO ALFONSO DAZA': 'Partido de la U',
    '2011_alcalde_LUIS GUSTAVO BONILLA RAMIREZ': 'Partido de la U',
    '2011_alcalde_LUIS JAIME AGUDELO CRISTANCHO': 'Partido Conservador Colombiano',
    '2011_alcalde_LUZ AMANDA CAMARGO VARGAS': 'Partido de la U',
    '2011_alcalde_MARCOS DANIEL BORDA PARRA': 'Partido de la U',
    '2011_alcalde_MARIO ANTONIO VILLAMARIN CRUZ': 'Partido de la U',
    '2011_alcalde_MIGUEL ANGEL ABRIL GARCIA': 'ASI',
    '2011_alcalde_MIGUEL ANGEL GARCIA PEREZ': 'Partido Liberal Colombiano',
    '2011_alcalde_MIGUEL ANGEL ZAMBRANO PINTO': 'Partido Conservador Colombiano',
    '2011_alcalde_MIGUEL ANTONIO CASTILLO BARRAGAN': 'Cambio Radical',
    '2011_alcalde_MIGUEL ANTONIO TORRES POVEDA': 'Partido Conservador Colombiano',
    '2011_alcalde_MIGUEL ARTURO RODRIGUEZ ROBAYO': 'ASI',
    '2011_alcalde_MILTON DIAZ BONILLA': 'Partido de la U',
    '2011_alcalde_NELSON DE JESUS MEDINA MERCHAN': 'Cambio Radical',
    '2011_alcalde_NELSON HERNANDO ROA RUBIO': 'Partido Liberal Colombiano',
    '2011_alcalde_NELSON ORLANDO RINCON SIERRA': 'Cambio Radical',
    '2011_alcalde_NELZON GARZON CHITIVA': 'Partido de la U',
    '2011_alcalde_NEYLA RUIZ CORREA': 'Alianza Verde',
    '2011_alcalde_OMAR CASALLAS SANCHEZ': 'Partido de la U',
    '2011_alcalde_OMAR VARGAS ALBARRACIN': 'Partido Conservador Colombiano',
    '2011_alcalde_ORLANDO CASTANEDA MONTENEGRO': 'Partido de la U',
    '2011_alcalde_OSCAR ENRIQUE AVILA GALAN': 'Alianza Verde',
    '2011_alcalde_OSCAR FERNANDO CALVO HURTADO': 'Partido de la U',
    '2011_alcalde_OSCAR HERNANDO PARRA APONTE': 'Alianza Verde',
    '2011_alcalde_OSCAR RICARDO CORREDOR QUINTERO': 'Alianza Verde',
    '2011_alcalde_PABLO MANUEL SOLANO ALVAREZ': 'Alianza Verde',
    '2011_alcalde_PABLO RICARDO LIZARAZO NAVAS': 'Partido Liberal Colombiano',
    '2011_alcalde_PLINIO ROLANDO FORERO DUENAS': 'Partido Conservador Colombiano',
    '2011_alcalde_RAMIRO BARRAGAN ADAME': 'Alianza Verde',
    '2011_alcalde_RAMIRO FONSECA CRUZ': 'Partido Conservador Colombiano',
    '2011_alcalde_REINALDO VERA AMAYA': 'Cambio Radical',
    '2011_alcalde_RICARDO VALBUENA MORENO': 'Alianza Verde',
    '2011_alcalde_RODRIGO HERNAN CARRILLO BALLESTEROS': 'Partido Conservador Colombiano',
    '2011_alcalde_SANDRA CELMIRA PEDROZA SANDOVAL': 'Partido Conservador Colombiano',
    '2011_alcalde_SANDRO RODOLFO BORDA ROJAS': 'Partido de la U',
    '2011_alcalde_SEGUNDO ANATOLIO PEDRAZA PARADA': 'Cambio Radical',
    '2011_alcalde_SEGUNDO CRISANTO OCHOA DIAZ': 'Partido de la U',
    '2011_alcalde_SERVILIO CAICEDO ULLOA': 'Partido Conservador Colombiano',
    '2011_alcalde_SILVIO ALBERTO RINCON ORTEGA': 'Partido Conservador Colombiano',
    '2011_alcalde_VIRGILIO FARFAN ROJAS': 'Movimiento Ciudadano',
    '2011_alcalde_WILDER IVAN SUESCA OCHOA': 'Partido Conservador Colombiano',
    '2011_alcalde_WILLIAM GUSTAVO PARRA MERCHAN': 'Partido Conservador Colombiano',
    '2011_alcalde_WILMER ENRIQUE SANABRIA NINO': 'Partido Liberal Colombiano',
    '2011_alcalde_WILSON FERNANDO BARON GOMEZ': 'Partido de Integración Nacional',
    '2011_alcalde_WILSON GUERRERO VASQUEZ': 'Partido Conservador Colombiano',
    '2011_alcalde_WILSON RICARDO BAEZ SOLANO': 'Partido Conservador Colombiano',
    '2011_alcalde_YURY NEILL DIAZ ARANGUREN': 'Movimiento Ciudadano',

    // ── 2011 GOBERNADOR ──
    '2011_gobernador_GONZALO GUARIN VIVAS': 'Alianza Verde',
    '2011_gobernador_JUAN CARLOS GRANADOS BECERRA': 'Partido de la U',
    '2011_gobernador_LEON RIGOBERTO BARON NEIRA': 'Partido Conservador Colombiano',

    // ── 2015 ALCALDE ──
    '2015_alcalde_ALBERTO RINCON GUZMAN': 'Partido Conservador Colombiano',
    '2015_alcalde_ALFONSO MIGUEL SILVA PESCA': 'Partido Conservador Colombiano',
    '2015_alcalde_ALFREDO CARO PUIN': 'Partido Liberal Colombiano',
    '2015_alcalde_ANATOLIO JOSE BENITO ALVARADO': 'Centro Democrático',
    '2015_alcalde_ANCISAR PARRA AVILA': 'Partido de la U',
    '2015_alcalde_ANGELA PATRICIA AVILA HAMON': 'Movimiento Ciudadano',
    '2015_alcalde_BENJAMIN EDILSON PINEROS ALFONSO': 'Partido de la U',
    '2015_alcalde_CAMILO SASTOQUE LEIVA': 'Partido Liberal Colombiano',
    '2015_alcalde_CARLOS ALBERTO ACEVEDO VELASQUEZ': 'Centro Democrático',
    '2015_alcalde_CARLOS ARTURO CUEVAS GOMEZ': 'Partido de la U',
    '2015_alcalde_CARLOS AUGUSTO SALINAS MEDINA': 'Movimiento Ciudadano',
    '2015_alcalde_CARLOS EDUARDO LUIS VANEGAS': 'Partido Liberal Colombiano',
    '2015_alcalde_CARLOS HERNANDO PERILLA ALDANA': 'Partido Liberal Colombiano',
    '2015_alcalde_CARLOS JULIO MELO ALDANA': 'Partido de la U',
    '2015_alcalde_CARLOS SAUL REYES ESTUPINAN': 'Partido de la U',
    '2015_alcalde_CESAR AUGUSTO CARRILLO ORTEGON': 'Partido de la U',
    '2015_alcalde_CLEMENTINA GUAYACAN GUEVARA': 'Partido Liberal Colombiano',
    '2015_alcalde_DAIRO RUBEN HERRERA PEREZ': 'Partido Liberal Colombiano',
    '2015_alcalde_DAVID JACINTO MONTERO CRUZ': 'Partido Conservador Colombiano',
    '2015_alcalde_DIEGO ARMANDO LOPEZ WANUMEN': 'Centro Democrático',
    '2015_alcalde_DUMAR FABIAN LOZANO VARGAS': 'Partido de la U',
    '2015_alcalde_EDGAR ANTONIO MORENO CHAPARRO': 'Movimiento Ciudadano',
    '2015_alcalde_EDGAR CRUZ CRISTANCHO CRISTANCHO': 'Partido Liberal Colombiano',
    '2015_alcalde_EDGAR ROBERTO PARRA ROA': 'Partido Liberal Colombiano',
    '2015_alcalde_EDUAR ALEXIS TRIANA RINCON': 'Partido Liberal Colombiano',
    '2015_alcalde_EDWIN CRISANTO BOHORQUEZ MORA': 'Alianza Verde',
    '2015_alcalde_ELIN JOSE BOHORQUEZ ARIZA': 'Cambio Radical',
    '2015_alcalde_ELIS ALEXANDER MORENO SALAMANCA': 'Centro Democrático',
    '2015_alcalde_ELKIN ALEJANDRO RINCON SALAMANCA': 'Movimiento Ciudadano',
    '2015_alcalde_EULICES AUGUSTO CARO CARO': 'Partido Conservador Colombiano',
    '2015_alcalde_FABIAN RICARDO GARCIA CAMARGO': 'Partido de la U',
    '2015_alcalde_FELIPE ABSALON CARDOZO MONTANA': 'Partido Conservador Colombiano',
    '2015_alcalde_FRANCISCO JAVIER ROA MILLAN': 'Partido Liberal Colombiano',
    '2015_alcalde_FRANKLY ORDUZ ACEVEDO': 'Partido Conservador Colombiano',
    '2015_alcalde_FRANKY ARIEL FONSECA SALAMANCA': 'Cambio Radical',
    '2015_alcalde_FREDY EDUARDO MARTINEZ VALDERRAMA': 'ASI',
    '2015_alcalde_GERARDO RINCON CAMACHO': 'Partido Conservador Colombiano',
    '2015_alcalde_GERMAN RICARDO ROBAYO HEREDIA': 'Partido Liberal Colombiano',
    '2015_alcalde_GLORIA EDY GOMEZ LOPEZ': 'Centro Democrático',
    '2015_alcalde_GUSTAVO TENJO RODRIGUEZ': 'Partido Liberal Colombiano',
    '2015_alcalde_HECTOR ANTONIO AMADO': 'Partido Liberal Colombiano',
    '2015_alcalde_HECTOR MIGUEL MOJICA MOJICA': 'ASI',
    '2015_alcalde_HELI QUINTERO SUAREZ': 'Alianza Verde',
    '2015_alcalde_HENRY ARGUELLO RINCON': 'Centro Democrático',
    '2015_alcalde_HENRY HERNANDO CHACON ZAMORA': 'Alianza Verde',
    '2015_alcalde_HERIBERTO SUAREZ MUNOZ': 'Partido de la U',
    '2015_alcalde_HUGO ALEXANDER REYES PARRA': 'Partido Liberal Colombiano',
    '2015_alcalde_INOCENCIO PEREZ CASTRO': 'Partido de la U',
    '2015_alcalde_ISAIAS NEIRA RIOS': 'Partido Liberal Colombiano',
    '2015_alcalde_JAIME ENRIQUE GALVIS HERNANDEZ': 'Centro Democrático',
    '2015_alcalde_JAIRO ALONSO RINCON QUINTANA': 'Partido Conservador Colombiano',
    '2015_alcalde_JAIRO CORDOBA SUAREZ': 'Partido Conservador Colombiano',
    '2015_alcalde_JAIRO ENRIQUE AHUMADA CASTANEDA': 'Partido Liberal Colombiano',
    '2015_alcalde_JAIRO ENRIQUE MILLAN MALPICA': 'Alianza Verde',
    '2015_alcalde_JANSSON TELLEZ RODRIGUEZ': 'Partido Conservador Colombiano',
    '2015_alcalde_JAVIER ORLANDO SUESCUN CARDENAS': 'Centro Democrático',
    '2015_alcalde_JHON ALEXANDER LOPEZ MENDOZA': 'Partido Conservador Colombiano',
    '2015_alcalde_JOHN JAIVER BLANCO LOPEZ': 'Partido Liberal Colombiano',
    '2015_alcalde_JORGE ALBERTO HURTADO LEON': 'Cambio Radical',
    '2015_alcalde_JORGE EDICSON SAAVEDRA VELASCO': 'Movimiento Ciudadano',
    '2015_alcalde_JOSE ABEL NOVA GUERRERO': 'Partido Conservador Colombiano',
    '2015_alcalde_JOSE DEL BARRERA PASTRAN': 'Partido Liberal Colombiano',
    '2015_alcalde_JOSE DEL DELGADO ZARATE': 'Cambio Radical',
    '2015_alcalde_JOSE JACINTO MORALES SANABRIA': 'Centro Democrático',
    '2015_alcalde_JOSE ROLDAN MALDONADO PEREZ': 'Partido Conservador Colombiano',
    '2015_alcalde_JOSE RUBIEL PAEZ': 'Partido Liberal Colombiano',
    '2015_alcalde_JULIO CESAR NEIRA CASTRO': 'Partido Liberal Colombiano',
    '2015_alcalde_JULIO ERNESTO SANABRIA GUERRA': 'Partido de la U',
    '2015_alcalde_JUSTO PASTOR RODRIGUEZ HERRERA': 'ASI',
    '2015_alcalde_KAROL RICARDO RAMIREZ SILVA': 'Partido de la U',
    '2015_alcalde_LEONARDO ALFONSO LOPEZ': 'Partido de la U',
    '2015_alcalde_LEONARDO JONHY PATINO QUIJANO': 'Cambio Radical',
    '2015_alcalde_LISSETH CAROLINA TORRES MANCHEGO': 'Partido de la U',
    '2015_alcalde_LUIS ALEJANDRO MILLAN DIAZ': 'Cambio Radical',
    '2015_alcalde_LUIS ARMANDO CALDAS FLORIAN': 'Partido Conservador Colombiano',
    '2015_alcalde_LUIS CARLOS CHIA HERNANDEZ': 'Partido de la U',
    '2015_alcalde_LUIS CARLOS CRUZ LOPEZ': 'Partido de la U',
    '2015_alcalde_LUIS ENRIQUE GIL VARGAS': 'Partido de la U',
    '2015_alcalde_LUIS FELIPE HIGUERA ROBLES': 'Partido Liberal Colombiano',
    '2015_alcalde_LUIS HERNANDO CALIXTO PAIPA': 'Cambio Radical',
    '2015_alcalde_LUIS MARIO VARGAS BERNAL': 'Partido Conservador Colombiano',
    '2015_alcalde_MARCO RODRIGO PEREZ PEREZ': 'Centro Democrático',
    '2015_alcalde_MARIA ELENA ORTIZ NOVA': 'Partido Liberal Colombiano',
    '2015_alcalde_MARIA ELISA MONTANEZ PARRA': 'Partido de la U',
    '2015_alcalde_MAURICIO NEISA ALVARADO': 'Cambio Radical',
    '2015_alcalde_MELQUISEDEC SALGADO ZUBIETA': 'Partido de la U',
    '2015_alcalde_MILTON OSWALDO FERNANDEZ ALFONSO': 'Partido de la U',
    '2015_alcalde_NABOR FELIPE LONDONO GORDILLO': 'Partido Conservador Colombiano',
    '2015_alcalde_NELSON HUMBERTO MELGAREJO ANGARITA': 'Partido de la U',
    '2015_alcalde_NELSON JAVIER GARCIA CASTELLANOS': 'Alianza Verde',
    '2015_alcalde_NESTOR ALONSO CASTILLO BUITRAGO': 'Partido Liberal Colombiano',
    '2015_alcalde_NUBIA ESPERANZA GOMEZ BRICENO': 'Centro Democrático',
    '2015_alcalde_OMAR JUNCO ESPINOSA': 'Partido Liberal Colombiano',
    '2015_alcalde_OSCAR FERNANDO BOTERO ALZATE': 'Partido Conservador Colombiano',
    '2015_alcalde_OSCAR IBAN CARDENAS CARO': 'Partido de la U',
    '2015_alcalde_OSCAR LEONARDO AVILA ROMERO': 'Alianza Verde',
    '2015_alcalde_PABLO EMILIO CEPEDA NOVOA': 'Cambio Radical',
    '2015_alcalde_PABLO ROBERTO ESTUPINAN SEPULVEDA': 'Centro Democrático',
    '2015_alcalde_PARMENIO DE JESUS RIVERA ROJAS': 'Partido Liberal Colombiano',
    '2015_alcalde_PEDRO ADOLFO BARRETO ABAUNZA': 'Partido Liberal Colombiano',
    '2015_alcalde_PEDRO MIGUEL LOPEZ VELA': 'Partido Liberal Colombiano',
    '2015_alcalde_RAMIRO ALEXANDER SUAREZ LOPEZ': 'Partido Liberal Colombiano',
    '2015_alcalde_RAMIRO DAZA MORA': 'Partido Conservador Colombiano',
    '2015_alcalde_RAUL DANIEL CUBIDES PINEDA': 'Partido Conservador Colombiano',
    '2015_alcalde_REYES BERNARDO PEREZ ALVAREZ': 'Cambio Radical',
    '2015_alcalde_RODRIGO ANCIZAR SANCHEZ SUAREZ': 'Partido Liberal Colombiano',
    '2015_alcalde_ROOSEVELT ALFONSO CHAVEZ LEGUIZAMON': 'Partido de la U',
    '2015_alcalde_RUBEN SANCHEZ NINO': 'Alianza Verde',
    '2015_alcalde_SALOMON DIAZ GUTIERREZ': 'Centro Democrático',
    '2015_alcalde_SANDRO NESTOR CONDIA PEREZ': 'Partido de la U',
    '2015_alcalde_SEGUNDO ANDRES CUITIVA JIMENEZ': 'Partido Conservador Colombiano',
    '2015_alcalde_SEGUNDO JACINTO PEREZ ARCHILA': 'Movimiento Ciudadano',
    '2015_alcalde_VICTOR HUGO FORERO SANCHEZ': 'Partido de la U',
    '2015_alcalde_VICTOR HUGO SILVA MOTTA': 'Partido Liberal Colombiano',
    '2015_alcalde_WILLIAM ENRIQUE PEREIRA HERRERA': 'Centro Democrático',
    '2015_alcalde_WILLINTHON JAIME ALFONSO PRIETO': 'Partido de la U',
    '2015_alcalde_WILMER YAIR CASTELLANOS HERNANDEZ': 'Cambio Radical',
    '2015_alcalde_WILSON CASTIBLANCO GIL': 'Partido de la U',
    '2015_alcalde_YAMIT ARIEL AVILA NINO': 'Centro Democrático',
    '2015_alcalde_YAMIT NOE HURTADO NEIRA': 'Alianza Verde',
    '2015_alcalde_YOANI VELA BERNAL': 'Partido de la U',
    '2015_alcalde_YOLANDA SALAZAR SIERRA': 'Partido de la U',
    '2015_alcalde_ZAMIR SOTELO MONROY': 'Alianza Verde',

    // ── 2015 GOBERNADOR ──
    '2015_gobernador_CARLOS ANDRES AMAYA RODRIGUEZ': 'Alianza Verde',
    '2015_gobernador_CESAR AUGUSTO PACHON ACHURY': 'Pacto Histórico',
    '2015_gobernador_GONZALO GUARIN VIVAS': 'Centro Democrático',
    '2015_gobernador_OSMAN HIPOLITO ROA SARMIENTO': 'Cambio Radical',

    // ── 2019 ALCALDE ──
    '2019_alcalde_ALFREDO HERNANDO NI├ÆO SIERRA': 'Partido Liberal Colombiano',
    '2019_alcalde_ALSILVER SIERRA MENDIETA': 'Partido Conservador Colombiano',
    '2019_alcalde_ALVARO HENRY BARRERA DIAZ': 'Partido Conservador Colombiano',
    '2019_alcalde_AURA BENILDA TEGRIA CRISTANCHO': 'MAIS',
    '2019_alcalde_AURORA DEL CARMEN NIETO MOLINA': 'Partido de la U',
    '2019_alcalde_BEATRIZ PAEZ CASTELLANOS': 'Alianza Verde',
    '2019_alcalde_BENJAMIN PEREZ CRISTANCHO': 'Alianza Verde',
    '2019_alcalde_CAMILO ANDRES CAICEDO SILVA': 'Cambio Radical',
    '2019_alcalde_CARLOS ALBERTO AVILA CEPEDA': 'AICO',
    '2019_alcalde_CARLOS JAVIER GUTIERREZ SANDOVAL': 'Centro Democrático',
    '2019_alcalde_CARLOS NELSON DIAZ PEREZ': 'Partido de la U',
    '2019_alcalde_CONSTANZA ISABEL RAMIREZ ACEVEDO': 'Cambio Radical',
    '2019_alcalde_DANIEL LOPEZ VALLEJO': 'Alianza Verde',
    '2019_alcalde_DIDIER AURELIO MARTINEZ VARGAS': 'Centro Democrático',
    '2019_alcalde_EDBERTO JOSE JAIME COCUNUBO': 'Partido Conservador Colombiano',
    '2019_alcalde_EDISON MANUEL APARICIO ARISMENDY': 'Partido Conservador Colombiano',
    '2019_alcalde_EDISON ROLANDO GAITAN ROA': 'Alianza Verde',
    '2019_alcalde_EDWARD EDIXON ARCHILA GONZALEZ': 'Partido Liberal Colombiano',
    '2019_alcalde_EDWIN RENE PAVA RINCON': 'Cambio Radical',
    '2019_alcalde_ELDER ACU├ÆA SANCHEZ': 'Partido Liberal Colombiano',
    '2019_alcalde_ELKIN YAMID SUAREZ PACHECO': 'Alianza Verde',
    '2019_alcalde_EMILIANO ALFONSO CHAPARRO FONSECA': 'Alianza Verde',
    '2019_alcalde_ERICA PAOLA PE├ÆA ALVAREZ': 'Cambio Radical',
    '2019_alcalde_ERIVERTO CRUZ RIA├ÆO': 'Partido Liberal Colombiano',
    '2019_alcalde_ERMES URIEL COMBITA SANTANA': 'Partido Liberal Colombiano',
    '2019_alcalde_EVELIO PUENTES ROCHA': 'Alianza Verde',
    '2019_alcalde_FABIAN ARMANDO SILVA SANCHEZ': 'Centro Democrático',
    '2019_alcalde_FABIO ALBERTO MEDRANO REYES': 'Alianza Verde',
    '2019_alcalde_FABIO AUGUSTO AREVALO': 'MAIS',
    '2019_alcalde_FABIO FIGUEROA JIMENEZ': 'Alianza Verde',
    '2019_alcalde_FIYER ALEXANDER URREGO BEJARANO': 'Alianza Verde',
    '2019_alcalde_FLAVIO HERNAN LARGO DURAN': 'Centro Democrático',
    '2019_alcalde_FRANCISCO JAVIER VILLAMIL': 'Cambio Radical',
    '2019_alcalde_FREDY ALEXANDER GARZON ROJAS': 'Alianza Verde',
    '2019_alcalde_FREDY ALEXANDER HOLGUIN RUIZ': 'Alianza Verde',
    '2019_alcalde_GERMAN AUGUSTO SANCHEZ SANCHEZ': 'Partido Liberal Colombiano',
    '2019_alcalde_GLORIA CECILIA PALACIOS GUASTAR': 'Partido Conservador Colombiano',
    '2019_alcalde_GREGORIO RODRIGUEZ SOLER': 'Partido Conservador Colombiano',
    '2019_alcalde_GUSTAVO ALEXANDER GARCIA PARRA': 'Partido Liberal Colombiano',
    '2019_alcalde_HECTOR ORLANDO BARRERA CARDENAS': 'Partido Conservador Colombiano',
    '2019_alcalde_HECTOR WILSON CASTELBLANCO RODRIGUEZ': 'Alianza Verde',
    '2019_alcalde_HENRY IVAN MATALLANA TORRES': 'Centro Democrático',
    '2019_alcalde_HENRY SANTIAGO SUTA TOCA': 'MAIS',
    '2019_alcalde_HUGO BUITRAGO': 'Partido Liberal Colombiano',
    '2019_alcalde_IMER YARIDMA MURCIA MONROY': 'Alianza Verde',
    '2019_alcalde_ISNARDO ALFONSO CASTELLANOS PE├ÆA': 'Partido Liberal Colombiano',
    '2019_alcalde_IVAN CAMILO CAMERO ALFONSO': 'Cambio Radical',
    '2019_alcalde_JAIME YESID RODRIGUEZ ROMERO': 'Centro Democrático',
    '2019_alcalde_JAIRO GRIJALBA LANCHEROS': 'Centro Democrático',
    '2019_alcalde_JAVIER ANDRES SOLANO ROJAS': 'Centro Democrático',
    '2019_alcalde_JEFERSON LEONARDO ORTIZ SANABRIA': 'Partido Liberal Colombiano',
    '2019_alcalde_JESUS NOE RIVEROS LOPEZ': 'Partido de la U',
    '2019_alcalde_JHON ALEXANDER ORTIZ SISSA': 'Alianza Verde',
    '2019_alcalde_JICLY ESGARDO MUTIS ISAZA': 'Cambio Radical',
    '2019_alcalde_JIMENO GARCIA GARCIA': 'Alianza Verde',
    '2019_alcalde_JOHN SANTIAGO RUIZ ALFONSO': 'Partido Conservador Colombiano',
    '2019_alcalde_JORGE MARIO IBA├ÆEZ ARANGO': 'Centro Democrático',
    '2019_alcalde_JOSE ALIRIO OCHICA PEREZ': 'Alianza Verde',
    '2019_alcalde_JOSE CLODOMIRO ARIZA PARDO': 'MAIS',
    '2019_alcalde_JOSE FERNANDO ROA ORJUELA': 'Alianza Verde',
    '2019_alcalde_JOSE HERNAN SIERRA BUITRAGO': 'Centro Democrático',
    '2019_alcalde_JOSE LUIS GOMEZ ALFONSO': 'Centro Democrático',
    '2019_alcalde_JOSE MIGUEL VELANDIA ALARCON': 'Cambio Radical',
    '2019_alcalde_JOSE MISAEL NEVA OCACION': 'Partido de la U',
    '2019_alcalde_JOSE MOISES AGUIRRE SANABRIA': 'Partido Liberal Colombiano',
    '2019_alcalde_JOSE MOISES CASTILLO DUARTE': 'Partido Conservador Colombiano',
    '2019_alcalde_JOSUE JAVIER CASTELLANOS MORALES': 'Alianza Verde',
    '2019_alcalde_JUAN ALCIBIADES CELY AMAYA': 'Partido Conservador Colombiano',
    '2019_alcalde_JUAN CARLOS BUITRAGO SALGADO': 'ASI',
    '2019_alcalde_JUAN DE JESUS ESTUPI├ÆAN PEREZ': 'Centro Democrático',
    '2019_alcalde_JUAN DIEGO MORALES CALDERON': 'Partido de la U',
    '2019_alcalde_JUAN YESID CUSBA TIBADUIZA': 'Partido de la U',
    '2019_alcalde_LEONARDO VEGA BUSTOS': 'Cambio Radical',
    '2019_alcalde_LUIS ALBERTO APONTE GOMEZ': 'Alianza Verde',
    '2019_alcalde_LUIS ALEJANDRO FUNEME GONZALEZ': 'Partido Conservador Colombiano',
    '2019_alcalde_MANUEL ALEJANDRO TAMBO RODRIGUEZ': 'Alianza Verde',
    '2019_alcalde_MARCO FIDEL SILVA ROJAS': 'Partido Conservador Colombiano',
    '2019_alcalde_MAYERLY BAEZ MERCHAN': 'Partido de la U',
    '2019_alcalde_MERY MOZO FONSECA': 'Partido Liberal Colombiano',
    '2019_alcalde_MIGUEL ANTONIO CASTILLO BARRAGAN': 'Cambio Radical',
    '2019_alcalde_MIGUEL ANTONIO MORA VALLEJO': 'Partido Liberal Colombiano',
    '2019_alcalde_MILTON DIAZ BONILLA': 'Alianza Verde',
    '2019_alcalde_NEICER ALBEIRO SUSA SOTELO': 'Partido Conservador Colombiano',
    '2019_alcalde_NELSON BOHORQUEZ OTALORA': 'Partido Conservador Colombiano',
    '2019_alcalde_NELSON PEREZ SUAREZ': 'Cambio Radical',
    '2019_alcalde_NEYDER MAURICIO OBANDO FORERO': 'Alianza Verde',
    '2019_alcalde_NUBIA JACQUELINE CARO PEREZ': 'Partido Liberal Colombiano',
    '2019_alcalde_ORLANDO CASTA├ÆEDA MONTENEGRO': 'Partido de la U',
    '2019_alcalde_OSCAR EDUARDO BOADA CASTRO': 'ASI',
    '2019_alcalde_OSCAR TRIVI├ÆO GIL': 'Partido Conservador Colombiano',
    '2019_alcalde_OSCAR YAMID RAMIREZ LOPEZ': 'Partido Liberal Colombiano',
    '2019_alcalde_OSCAR YOVANY MONTENEGRO SALCEDO': 'Partido Conservador Colombiano',
    '2019_alcalde_OSWALDO PEREZ QUIROZ': 'Centro Democrático',
    '2019_alcalde_PABLO ANTONIO BERNAL SANCHEZ': 'Centro Democrático',
    '2019_alcalde_PEDRO ALONSO AGUILLON PUENTES': 'Partido Conservador Colombiano',
    '2019_alcalde_PEDRO ANTONIO LOPEZ PRIETO': 'Partido Conservador Colombiano',
    '2019_alcalde_PEDRO ANTONIO MURILLO MORENO': 'Partido Liberal Colombiano',
    '2019_alcalde_RAFAEL ANTONIO FONSECA CELY': 'Partido de la U',
    '2019_alcalde_RAFAEL ANTONIO RATIVA DIAZ': 'Partido Liberal Colombiano',
    '2019_alcalde_RAFAEL ERNESTO RAMIREZ VALERO': 'Partido Conservador Colombiano',
    '2019_alcalde_RAMIRO FONSECA CRUZ': 'Centro Democrático',
    '2019_alcalde_RAUL FERNANDO MORENO WALTEROS': 'Partido Liberal Colombiano',
    '2019_alcalde_RAUL HERNANDO RODRIGUEZ CHAVARRO': 'Alianza Verde',
    '2019_alcalde_RIGOBERTO ALFONSO PEREZ': 'Alianza Verde',
    '2019_alcalde_ROBINSON LEANDRO SALAMANCA RINCON': 'Centro Democrático',
    '2019_alcalde_RONALD GERARDO CORDERO JAIME': 'Alianza Verde',
    '2019_alcalde_SANDRO RODOLFO BORDA ROJAS': 'Partido de la U',
    '2019_alcalde_SEGUNDO ALDEMAR TOCA SUAREZ': 'Alianza Verde',
    '2019_alcalde_SEGUNDO CRISANTO OCHOA DIAZ': 'Partido de la U',
    '2019_alcalde_SILVIO ALBERTO RINCON ORTEGA': 'Partido Conservador Colombiano',
    '2019_alcalde_TOMAS RUIZ SILVA': 'Centro Democrático',
    '2019_alcalde_WILBLIN YESID SOTO MONROY': 'Cambio Radical',
    '2019_alcalde_WILLIAM EUSEBIO CORREA DURAN': 'Centro Democrático',
    '2019_alcalde_WILLIAM GUSTAVO PARRA MERCHAN': 'Partido Conservador Colombiano',
    '2019_alcalde_WILMAR ANCISAR TRIANA GONZALEZ': 'Cambio Radical',
    '2019_alcalde_WILMAR JULIAN RINCON MARI├ÆO': 'Alianza Verde',
    '2019_alcalde_WILSON FERNANDO BARON GOMEZ': 'Partido Conservador Colombiano',
    '2019_alcalde_WILSON ISAY MORENO VEGA': 'Partido Conservador Colombiano',
    '2019_alcalde_WILSON RICARDO BAEZ SOLANO': 'Cambio Radical',
    '2019_alcalde_WILTON GIOVANI RUIZ CORREA': 'Alianza Verde',
    '2019_alcalde_WYLLAN ORLANDO PE├ÆALOZA ALBARRACIN': 'Alianza Verde',
    '2019_alcalde_YAMITH RODRIGO RODRIGUEZ LOPEZ': 'Partido Conservador Colombiano',
    '2019_alcalde_ZANDRA MARIA BERNAL RINCON': 'Partido Conservador Colombiano',

    // ── 2019 GOBERNADOR ──
    '2019_gobernador_JONATAN SANCHEZ GARAVITO': 'Centro Democrático',
    '2019_gobernador_JOSE GIOVANY PINZON BAEZ': 'Pacto Histórico',
    '2019_gobernador_RAMIRO BARRAGAN ADAME': 'Alianza Verde',

    // ── 2023 ALCALDE ──
    '2023_alcalde_ADIEL PANQUEBA CHIA': 'Partido de la U',
    '2023_alcalde_ALBA MERLY MARANTA CONTRERAS': 'Alianza Verde',
    '2023_alcalde_ALBERTO SANDOVAL VALCARCEL': 'Alianza Verde',
    '2023_alcalde_ALCIDES FLORIDO PABON': 'Alianza Verde',
    '2023_alcalde_ALEJANDRO MU├ÆOZ SANDOVAL': 'Partido Liberal Colombiano',
    '2023_alcalde_ALVARO EFRAIN ROJAS BERMUDEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_ARMANDO TARAZONA GALLO': 'Centro Democrático',
    '2023_alcalde_CABETO PEREZ DIAZ': 'Partido Liberal Colombiano',
    '2023_alcalde_CAMILO ANDRES AVILA MARQUEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_CARLOS ALBERTO AMADOR RAMOS': 'Partido Liberal Colombiano',
    '2023_alcalde_CARLOS ALBERTO CASTELLANOS GOMEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_CARLOS ANDRES COCUNUBO BLANCO': 'Alianza Verde',
    '2023_alcalde_CARLOS DAVID ZARATE BAEZ': 'En Marcha',
    '2023_alcalde_CARLOS SAUL REYES ESTUPI├ÆAN': 'Partido de la U',
    '2023_alcalde_CESAR DANILO MEDINA MANRIQUE': 'Partido de la U',
    '2023_alcalde_CIRO ALFONSO CASTELLANOS PAEZ': 'ASI',
    '2023_alcalde_CLAUDIO ALFONSO COY GUERRA': 'Alianza Verde',
    '2023_alcalde_DARIO MONTA├ÆEZ PE├ÆA': 'Partido Conservador Colombiano',
    '2023_alcalde_DAVID FRANCISCO MORALES CASTILLO': 'Alianza Verde',
    '2023_alcalde_DIANA ELIZABETH RIA├ÆO CHAPARRO': 'Alianza Verde',
    '2023_alcalde_DIEGO ALEJANDRO LANCHEROS RUIZ': 'Partido Liberal Colombiano',
    '2023_alcalde_DIEGO FERNANDO RIVERA VELANDIA': 'Partido Liberal Colombiano',
    '2023_alcalde_DONALD ARLEY AGUDELO ALFONSO': 'Partido Conservador Colombiano',
    '2023_alcalde_EDGAR ALEXANDER AVELLA FLOREZ': 'Centro Democrático',
    '2023_alcalde_EDGAR GERARDO DIAZ ANGARITA': 'Partido de la U',
    '2023_alcalde_EDGAR RICARDO GAMEZ AMAYA': 'ASI',
    '2023_alcalde_EDISON FABIAN PATI├ÆO SIABATTO': 'Partido Conservador Colombiano',
    '2023_alcalde_EDUARDO SALCEDO VELOSA': 'Partido Conservador Colombiano',
    '2023_alcalde_EDWIN AUGUSTO ALMANZA QUINTERO': 'Cambio Radical',
    '2023_alcalde_EDWIN HARVEY ESPITIA LARA': 'Partido de la U',
    '2023_alcalde_EFRAIN CAMILO BERNAL YANQUEN': 'Alianza Verde',
    '2023_alcalde_ELKIN JESUS ALFONSO GIL': 'Alianza Verde',
    '2023_alcalde_EZEQUIEL JIMENEZ CELY': 'En Marcha',
    '2023_alcalde_FELIX ALEJANDRO GUTIERREZ VEGA': 'Cambio Radical',
    '2023_alcalde_FELKIN IVAN CASTELLANOS VALBUENA': 'Alianza Verde',
    '2023_alcalde_FREDY IOVANNY PARDO PINZON': 'Partido Liberal Colombiano',
    '2023_alcalde_GERARDO RINCON CAMACHO': 'Partido Conservador Colombiano',
    '2023_alcalde_GERMAN ALONSO BECERRA LOPEZ': 'Alianza Verde',
    '2023_alcalde_GERMAN CAMILO MORALES RINCON': 'Partido Liberal Colombiano',
    '2023_alcalde_GERMAN RICARDO CAMACHO BARRERA': 'Partido Liberal Colombiano',
    '2023_alcalde_GERMAN RICARDO ROBAYO HEREDIA': 'Partido de la U',
    '2023_alcalde_GILDARDO MURCIA BUITRAGO': 'Partido Conservador Colombiano',
    '2023_alcalde_GIOVANNI VELA BERNAL': 'Dignidad y Comp.',
    '2023_alcalde_GLORIA EDY GOMEZ LOPEZ': 'Alianza Verde',
    '2023_alcalde_HECTOR DAVID AMADO SIERRA': 'Partido de la U',
    '2023_alcalde_HECTOR SEGUNDO RAMIREZ ESCOBAR': 'Partido Liberal Colombiano',
    '2023_alcalde_HELVER RICARDO GRANADOS GUAUQUE': 'Cambio Radical',
    '2023_alcalde_HERNAN ALONSO ACOSTA MEDINA': 'Alianza Verde',
    '2023_alcalde_HUGO ALEXANDER REYES PARRA': 'Alianza Verde',
    '2023_alcalde_JAIME ARMANDO GOMEZ BUITRAGO': 'Alianza Verde',
    '2023_alcalde_JEFFERSON LEONARDO CARO CASAS': 'Partido Verde Oxígeno',
    '2023_alcalde_JESUS ALEJANDRO PUENTES MARTINEZ': 'Partido Liberal Colombiano',
    '2023_alcalde_JHON FEIBER URREA CIFUENTES': 'Partido Liberal Colombiano',
    '2023_alcalde_JORGE ALFONSO RAMIREZ GALINDO': 'Alianza Verde',
    '2023_alcalde_JORGE ANDRES ALARCON AVELLA': 'Partido Liberal Colombiano',
    '2023_alcalde_JORGE ENRIQUE VANEGAS PULIDO': 'Alianza Verde',
    '2023_alcalde_JOSE EUSTAQUIO ARIZA PARDO': 'Partido Liberal Colombiano',
    '2023_alcalde_JOSE JACINTO MORALES SANABRIA': 'Partido Liberal Colombiano',
    '2023_alcalde_JOSE JUVENAL TORRES CRISTANCHO': 'Partido Conservador Colombiano',
    '2023_alcalde_JOSE LUIS BOHORQUEZ LOPEZ': 'Pacto Histórico',
    '2023_alcalde_JUAN ALEXIS MARTINEZ FAJARDO': 'Partido de la U',
    '2023_alcalde_JUAN CARLOS GONZALEZ PINEDA': 'Partido Conservador Colombiano',
    '2023_alcalde_JUAN CARLOS SANCHEZ RINCON': 'Centro Democrático',
    '2023_alcalde_JUAN CARLOS SARMIENTO SARMIENTO': 'Nuevo Liberalismo',
    '2023_alcalde_JUAN DIEGO MORALES CALDERON': 'Partido de la U',
    '2023_alcalde_JULIO ALBERTO ROMERO CAMACHO': 'Movimiento Ciudadano',
    '2023_alcalde_JULIO CESAR RUBIANO CASAS': 'Alianza Verde',
    '2023_alcalde_JULIO ERNESTO SANABRIA GUERRA': 'Partido de la U',
    '2023_alcalde_JULIO RAMIRO PE├ÆA RAMIREZ': 'Centro Democrático',
    '2023_alcalde_JUVENAL PEREZ VEGA': 'Alianza Verde',
    '2023_alcalde_LEDYS SORAYA VERA MONROY': 'Partido de la U',
    '2023_alcalde_LEIDY PATRICIA CANO AVILA': 'Partido de la U',
    '2023_alcalde_LUIS CARLOS CHIA HERNANDEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_LUIS GUILLERMO BERRIO HERNANDEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_LUIS MARIO VARGAS BERNAL': 'Cambio Radical',
    '2023_alcalde_LUZ AMANDA RODRIGUEZ SALAMANCA': 'Centro Democrático',
    '2023_alcalde_MANUELA PIDIACHE RUIZ': 'Partido Conservador Colombiano',
    '2023_alcalde_MARCO AURELIO LOPEZ GOMEZ': 'Centro Democrático',
    '2023_alcalde_MARCOS DANIEL BORDA PARRA': 'Pacto Histórico',
    '2023_alcalde_MARIO EDILBERTO SIABATO RINCON': 'Partido Conservador Colombiano',
    '2023_alcalde_MARIO FERNANDO LOZANO DUARTE': 'Alianza Verde',
    '2023_alcalde_MARIO JOSE AVILA FURQUE': 'Partido Liberal Colombiano',
    '2023_alcalde_MAURICIO BARON GRANADOS': 'Partido Liberal Colombiano',
    '2023_alcalde_MIGUEL ANDRES RODRIGUEZ SAAVEDRA': 'Movimiento Ciudadano',
    '2023_alcalde_MIGUEL ANGEL SERRANO CELY': 'Partido de la U',
    '2023_alcalde_MIKHAIL KRASNOV': 'Partido Liberal Colombiano',
    '2023_alcalde_MILLER FAIR ROMERO MURCIA': 'Cambio Radical',
    '2023_alcalde_NANCY YANETH VACA GUTIERREZ': 'Partido Conservador Colombiano',
    '2023_alcalde_NELZON GARZON CHITIVA': 'Partido Conservador Colombiano',
    '2023_alcalde_NENDY JOSE FAGUA CAINA': 'Partido Liberal Colombiano',
    '2023_alcalde_NESTOR ARMANDO SUAREZ CETINA': 'En Marcha',
    '2023_alcalde_OSCAR ANTONIO HURTADO CARVAJAL': 'Partido Liberal Colombiano',
    '2023_alcalde_OSCAR CAMILO MONTA├ÆEZ BOHORQUEZ': 'MAIS',
    '2023_alcalde_OSCAR DARIO HURTADO PEREZ': 'Partido Conservador Colombiano',
    '2023_alcalde_PEDRONEL VILLAMIL CASTRO': 'Alianza Verde',
    '2023_alcalde_PLINIO HERNANDEZ GAMBA': 'Partido Conservador Colombiano',
    '2023_alcalde_PUPO ALONSO RINCON RINCON': 'Partido Conservador Colombiano',
    '2023_alcalde_RAFAEL ANTONIO SORA CAMARGO': 'Alianza Verde',
    '2023_alcalde_RAUL ANTONIO CUBIDES RAMIREZ': 'Partido de la U',
    '2023_alcalde_REINALDO TORRES': 'Alianza Verde',
    '2023_alcalde_RENE GUSTAVO TEJEDOR LOPEZ': 'Partido Liberal Colombiano',
    '2023_alcalde_RICARDO CRISTANCHO FERNANDEZ': 'Alianza Verde',
    '2023_alcalde_RODOLFO ANDRES TORRES AGUDELO': 'Partido Conservador Colombiano',
    '2023_alcalde_RODRIGO HERNAN CARRILLO BALLESTEROS': 'Alianza Verde',
    '2023_alcalde_RUBEN DARIO GONZALEZ GARCIA': 'Alianza Verde',
    '2023_alcalde_SALOMON BUITRAGO FONSECA': 'ASI',
    '2023_alcalde_SANTIAGO ALEXANDER VARGAS DAZA': 'Alianza Verde',
    '2023_alcalde_SEBASTIAN JUEZ ARIAS': 'Partido Liberal Colombiano',
    '2023_alcalde_VICTOR ALFONSO GAMBOA CHAPARRO': 'Partido Liberal Colombiano',
    '2023_alcalde_VIVIANA PAOLA MARTIN AREVALO': 'Partido Conservador Colombiano',
    '2023_alcalde_VLADIMIR RISCANEVO POBLADOR': 'Partido Conservador Colombiano',
    '2023_alcalde_WILBER JAIME SALAMANCA PINEDA': 'Partido Liberal Colombiano',
    '2023_alcalde_WILIAR PE├ÆA SUATERNA': 'ASI',
    '2023_alcalde_WILLIAM CAMILO BARRETO GONZALEZ': 'Partido Conservador Colombiano',
    '2023_alcalde_WILLIAM TOMAS GALINDO BORDA': 'Alianza Verde',
    '2023_alcalde_WILSON CASTIBLANCO GIL': 'Partido Liberal Colombiano',
    '2023_alcalde_WILSON FRANCISCO ARIAS GUERRA': 'Partido Conservador Colombiano',
    '2023_alcalde_WOLBERT VARGAS RINCON': 'Partido Verde Oxígeno',
    '2023_alcalde_XIMENA ELIZABETH CASTA├ÆEDA DE MOLINA': 'Alianza Verde',
    '2023_alcalde_YEISON ALBEIRO ALFONSO GAITAN': 'Alianza Verde',
    '2023_alcalde_YESID ALEXANDER BERNAL HERNANDEZ': 'Alianza Verde',
    '2023_alcalde_YOLANDA SALAZAR SIERRA': 'Partido de la U',
    '2023_alcalde_YON FREDY GONZALEZ HUERTAS': 'Alianza Verde',

    // ── 2023 GOBERNADOR ──
    '2023_gobernador_CARLOS ANDRES AMAYA RODRIGUEZ': 'Alianza Verde',
    '2023_gobernador_RODRIGO ARTURO ROJAS LARA': 'Partido Liberal Colombiano',
};
